### ISSUE TITLE
File ownership after processing steps

### ISSUE THREAD

**Issue by tblock79** [mercure-imaging/mercure#15]
Currently, files created during processing are owned by root (as created from within the docker container). Might create issues with systemd installation setup, as the systemd processes are not running as root. Need to find solution.

**Comment by joshy** [comment]
In the systemd file you can also specify a user under which user the service should run. Would that solve the problem?

**Comment by tblock79** [comment]
Not sure if this alone would solve it. Problem is that the user accounts of the host system don't map into the Docker container that executes the processing code. Currently, the processing code (inside the Docker container) is running as root, while the systemd services are running as non-root user (for security reasons). It might be possible to pass the UID and GID when starting the docker container, but need to check if this would also work with Nomad.

**Comment by tblock79** [comment]
Solved by commits 3b7c1601d4e7c4e0be17e3b6f983e715a03b9819 and 2a430acba0380a30b0756620d5f025b59dfa7879
