### ISSUE TITLE
Processing modules should be able to return results

### ISSUE THREAD

**Issue by RoyWiggins** [mercure-imaging/mercure#22]
Right now, processing steps can only produce dicoms. We should have some way to let them produce non-dicom results and have Mercure store them somewhere. 

A simple solution would be for the processor step to look for a `result.json` file in the output directory, and if it's present and valid JSON to consider the contents the results of the processing step. 

Where and how to store the results is another question. We already have the bookkeeper process, which is backed by a database. This is a natural place to stuff processing results (Postgres has robust support for json), except that the bookkeeper has until now been somewhat optional, with Mercure being able to receive, process, and route cases without it. 

It could be that the Mercure should actually refuse to function if the bookkeeper isn't available: with it turned off, there's no general way to determine the provenance of files it produces.

**Comment by tblock79** [comment]
Has been implemented.
