### ISSUE TITLE
Provenance tracking

### ISSUE THREAD

**Issue by RoyWiggins** [mercure-imaging/mercure#24]
While the events on a particular series is being tracked with the bookkeeper, there's no built-in method to actually see it. Exposing this information as a built-in dashboard would be useful for debugging and to make it more straightforward to demonstrate the functionality of the bookkeeper. 

This would also want to be able to display the log output of any processing module run.

**Comment by tblock79** [comment]
Available with commit 60d5d4db7e7ae549edd7a3fabcc4cb1be90d6c66
