### ISSUE TITLE
Rename default volumes `data` and `output` in order to avoid name collisions

### ISSUE THREAD

**Issue by averdones** [mercure-imaging/mercure#31]
**Is your feature request related to a problem? Please describe.**
One of the folders in the docker image that I created to use with mercure was called `data`. 

I didn't know at first why my program was failing at finding the subfolders and files inside my `data` folder, until I realized that mercure had also a folder called `data` that was overwriting my folder.

**Describe the solution you'd like**
Rename both `data` and `output` volumes in [here](https://github.com/mercure-imaging/mercure/blob/43ebd246912b2a47b7c6bcf660b4b3b84df568da/process/process_series.py#L118) as suggested by @tblock79.

@tblock79 suggested renaming them to something like `mercure_data` and `mercure_output`. I am thinking that adding an underscore in front could help even more (or something even more unique). I can see myself being silly enough to name a folder `mercure_data` just because I am working with mercure.

Also, the presence of this two folders and, in general, the folder structure of the docker image could be better documented somewhere. 

**Describe alternatives you've considered**

**Additional context**

**Comment by RoyWiggins** [comment]
I've moved the folders into `/tmp/`, which should solve the issue- it would be quite unlikely for a container to include important things in `/tmp`. 

[https://github.com/mercure-imaging/mercure/commit/a9deee2ca242f88d61262fca41460e6579f393e5](Commit here).
