### ISSUE TITLE
Contrast Tag & Dose Tag

### ISSUE THREAD

**Issue by Bordasludovic** [mercure-imaging/mercure#47]
Hello,

Is it possible to add the following tags:

0040,0310 = dose report
0018,0010 = contrast used

If yes, is it possible to create a rule of this type?

If the field exists and is filled then routing.
If the field is empty then no routing.

Thank you.

**Comment by tblock79** [comment]
Adding additional custom tags will be possible in the next release. We are currently implementing this feature.

**Comment by Bordasludovic** [comment]
Great news ! 

Do you have any idea when this new version will be released?

**Comment by tblock79** [comment]
The feature is now available on the DEV branch. We will do some more testing and then make a release in the next 2-3 weeks.

**Comment by tblock79** [comment]
The version 0.3.0-beta.1 that includes this feature has now been released.

**Comment by Bordasludovic** [comment]
Great!

How can i create a rule of this type?

If the field exists and is filled then routing.
If the field is empty then no routing.

Thank you.
