### ISSUE TITLE
live job queue status

### ISSUE THREAD

**Issue by dmd** [mercure-imaging/mercure#5]
It can be hard to glean what the current job queue is just from watching the logs. A more direct view into what jobs are actually running would be nice - an auto-updating view of what's being received, send, cleaned, etc. Can this be pulled out of `rq`?

**Comment by joshy** [comment]
On the command line you can run `rq info -i 1`which updates every second. You see the status of workers and total jobs but won't see what's begin received, send etc. That information should be available in redash.

**Comment by tblock79** [comment]
The new version has a Queue page in the web interface. Still works in progress to some degree but hopefully finished soon.
