### ISSUE TITLE
DIMSE Failed to receive message for multislice reformatted data

### ISSUE THREAD

**Issue by dmd** [mercure-imaging/mercure#50]
After turning our multiframe sending on at the scanner (see #49 ), we get a new error:

```
receiver_1    | 2023-04-24T20:39:02.657233386Z W: DcmItem: Parse error while parsing element (fffe,e000)
receiver_1    | 2023-04-24T20:39:02.657281575Z W: DIMSE Warning: (AWP1671091,mic-dicom-router): DIMSE receiveDataSetInMemory: dset->read() Failed (Invalid tag)
receiver_1    | 2023-04-24T20:39:02.658508858Z E: Store SCP Failed: 0006:020d DIMSE Failed to receive message
receiver_1    | 2023-04-24T20:39:02.658523904Z E: DIMSE failure (aborting association): 0006:020d DIMSE Failed to receive message
```

We get this only for (according to @bbfrederick ) "the multi slice reformatted data from the 3D T1 MPRAGE acquisition. The techs run the “parallel ranges” tool in MR view and go to make this series.".

This is not unique to mercure - we are getting a DIMSE error when sending to Orthanc as well (which I think but am not certain uses dcmtk's libraries internally) and Osirix MD (who knows, the Osirix fork is closed source, but Horos does use dcmtk).

Any ideas?

**Comment by dmd** [comment]
Adding @neurolabusc

**Comment by bbfrederick** [comment]
I might be able to go grab one after dinner. If not then tomorrow morning.

**Comment by bbfrederick** [comment]
I got a nice anonymous phantom dataset this evening, but whenever I reformat it, the transfer goes fine. I'll have one of the techs do it tomorrow - I don't think I'm doing the same thing.

**Comment by tblock79** [comment]
Closing this issue as it seems to be unrelated to mercure itself.
