### ISSUE TITLE
Unreachable endpoint when module name contains a slash

### ISSUE THREAD

**Issue by LennyN95** [mercure-imaging/mercure#64]
**Describe the bug**
I noticed the following behaviour: the UI currently allows the usage of `/` characters e.g. module names.
However, these module names are unable to be edited or deleted from the web GUI as the slash is not encoded and thus interpreted as part of the URL, consequently showing a `Not Found` error.

Huge thanks to the developers for building promising open-source tools like Mercure!

**To Reproduce**
1. Navigate to `http://localhost:8000/modules/`
2. Create new module, e.g. use name `Test/MyModel`
3. Click *Edit*
5. URL resolves to `http://localhost:8000/modules/edit/Test/MyModel` which will be "Not Found"

**Expected behavior**
Either prohibit the use of unencoded characters or better use URL encoding for model names.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 13.4.1 (c) (22F770820d)
 - Browser Firefox 119.0.1 (64-Bit)
 - Version 0.3.0-beta.2 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RoyWiggins** [comment]
The UI uses a `pattern` attribute on the input control to validate the module name, though there's no server-side validation. I'm not sure how Firefox let you submit the form in the first place, honestly- I can't replicate the issue. 

![image](https://github.com/mercure-imaging/mercure/assets/5290850/140fa1e0-9998-4153-92cd-120be04a855f)

**Comment by LennyN95** [comment]
Hey Roy, thx for picking this up. I'll look into this again and see if I can provide any valuable insights into why the front-end restriction didn't apply in my case.

I suggest re-consider implementing backend checks on all user inputs. 
UI restrictions are more of a UIX feature than reliable (and, of course, not secure).

**Comment by tblock79** [comment]
Seems that there was a bug in the regex expression used for restricting the input pattern (the - char was not escaped). This is fixed now, and also added a check on the backend.

Fixed with commit 3ed0a3d4932d77cef5976831809b968d1848f17c
