### ISSUE TITLE
No feedback when wanting to add a module on success or failure

### ISSUE THREAD

**Issue by MLK97** [mercure-imaging/mercure#70]
**Describe the bug**
I am currently trying to set up one of the modules in mercure you provide. To be precise the [Mercure-TestModule](https://mercure-imaging.org/docs/module_list.html#mercure-testmodule).
I followed the exact procedure, however, it does not work to install it. I assume this has to do something with the firewall settings we installed on the server where the mercure installation runs. 
What I think would be a nice addition is an error notification that displays that something went wrong and what exactly went wrong. Unfortunately, there is also no notification in the logs.

**To Reproduce**
1. Force the installation to fail (e.g. deactivate internet connection or change firewall settings)
2. Click on Modules
3. Click on Install Module
4. Use mercureimaging/mercure-testmodule as docker tag and have mercure selected
5. Click Install 

**Expected behavior**
An error message that no connection could be made to docker hub 

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 122

**Comment by MLK97** [comment]
A brief update since I investigated further. On opening the web browser console I see that it is caused by a 500 Server Error

![billede](https://github.com/mercure-imaging/mercure/assets/18293577/d1c4e86c-b00e-40c6-a7bb-c3c8b8e2e5ca)

**Comment by tblock79** [comment]
Display of an error message has been added in 7c9472c56bc263bb8348d2b3699db019715035d5. This is currently only in the dev version and will be part of the next release.
