### ISSUE TITLE
i m trying to add new module screen shot attached. but install button not clicked(not respond)

### ISSUE THREAD

**Issue by nitin271080** [mercure-imaging/mercure#71]
![Screenshot_2024-02-09_16-22-36](https://github.com/mercure-imaging/mercure/assets/38910107/5e5f2cc4-2fdc-4b4f-aff1-4d5833764830)
**Describe the bug**
i m trying to add new module screen shot attached. but install button not clicked(not respond)
 try this sudo journalctl -u mercure_ui.service

error showing
docker.errors.dockerexception error while fetching server api version(connection aborted.,permissionerror(13,'permission denied'))

**Comment by tblock79** [comment]
This looks like a configuration problem on your server. Make sure that the user running mercure (typically the user "mercure") has permissions for run docker commands. This usually requires that the user is added to the docker group under Linux. For instructions, visit this page:
https://docs.docker.com/engine/install/linux-postinstall/

We have recently added improved error reporting in the UI. This is currently only in the DEV version and will be part of the next release.
