### ISSUE TITLE
Support for Ubuntu 24.04

### ISSUE THREAD

**Issue by BluePython339** [mercure-imaging/mercure#81]
When installing the DICOM router, it errors out because it doesn't support Ubuntu 24.04, i assume this is a precaution to avoid any old versions of ubuntu running the software.

My request is, will there be an ubuntu 24.04 release and if so, any idea when, aswell are what are the issues that need to be fixed before it can be run on 24.04 (for possible pull request)

**Comment by BluePython339** [comment]
i let it install on 24.04, no errors seem to happend (as expected), will continue testing, and if its stable i'll create a pull request

**Comment by tblock79** [comment]
Support for Ubuntu 24.04 is now available in the dev version (head of the repository). We will create a new beta release soon.
