### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by cadrogui** [mercure-imaging/mercure#82]
Hi everyone, when i send a Study to mercure Ive got this error:

Oct 16 19:00:52 ip-172-1-64-57 receiver.sh[606386]: ERROR: Unable to perform character set conversion!
Oct 16 19:00:52 ip-172-1-64-57 receiver.sh[606386]: ERROR: Incoming charset is ISO 2022 IR 100

any ideas?
Regards.

**Comment by tblock79** [comment]
Duplicate issue: 
https://github.com/mercure-imaging/mercure/issues/59

**Comment by RoyWiggins** [comment]
@cadrogui possible resolution posted [here](https://github.com/mercure-imaging/mercure/issues/59#issuecomment-2429750477)
